### ISSUE TITLE
Input of further numbers stops when first digit is '1' in credit card expiry month

### ISSUE THREAD

**Issue by RyanLinXiang** [wgltony/react-native-braintree-dropin-ui#101]
In iOS the expiry month input field for credit card does not accept any other number when the number '1' is entered as first digit. The consequence is that the months 11 (November) and 12 (December) currently cannot be typed into the field as expiry month.

I first thought that the bug originates from the Braintree iOS drop in SDK, but when I installed the demo app, it turns out that the bug only occurs with the React Native version here.

**Comment by RyanLinXiang** [comment]
Obsolete. Bug occurs only with our implementation.

**Comment by mgdeveloper7** [comment]
I'm getting something similar on the iOS simulator.  I can type in a 0 or 1 in the expiry month but it won't let me type in anything else.

Works fine on a build on an actual device.

I'm using plug in version 1.1.7, but I experienced it on 1.1.5 before that.  Using React Native 0.72.4.

Anyone else experiencing this?
