### ISSUE TITLE
Credit Card payment option not showing in Select payment method

### ISSUE THREAD

**Issue by Jigs6720** [wgltony/react-native-braintree-dropin-ui#113]
Select payment method Card option is not showing anymore in the dropin ui.

**Comment by Jigs6720** [comment]
![Screenshot_1692277393](https://github.com/wgltony/react-native-braintree-dropin-ui/assets/114900753/ca2d3553-2cbb-43d1-b31f-66936e8598c1)

**Comment by pckz** [comment]
@Jigs6720 did you solve it? same for me
