### ISSUE TITLE
App rejected: SDK: Cardinal Commerce org.jfrog.cardinalcommerce.gradle:cardinalmobilesdk (consider upgrading to version 2.2.7-2)

### ISSUE THREAD

**Issue by Osmon11** [wgltony/react-native-braintree-dropin-ui#118]
package.json:

"react-native": "0.72.6",
"react-native-braintree-dropin-ui": "1.1.5",

app/build.gradle:

implementation 'com.braintreepayments.api:drop-in:6.11.0'

I also tried

implementation 'org.jfrog.cardinalcommerce.gradle:cardinalmobilesdk:2.2.7-2'

but it still getting rejected.
Any help would be appreciated.

**Comment by Osmon11** [comment]
Downgrading helped me resolve the issue.

"react-native-braintree-dropin-ui": "^1.1.1",

**Comment by Osmon11** [comment]
Make sure you don’t have another track with an older version of the SDK. I had an older version on a closed track that was causing the rejection.

**Comment by ARSSHEIKH** [comment]
> Downgrading helped me resolve the issue.
> 
> "react-native-braintree-dropin-ui": "^1.1.1",

not solved
