### ISSUE TITLE
 GoogleMerchantID is Missing ???

### ISSUE THREAD

**Issue by mkharibalaji** [wgltony/react-native-braintree-dropin-ui#16]
Hi @wgltony,
         How do i configure the GoogleMerchantID ?

Thanks & regards,
Hari

**Comment by soarb** [comment]
I was wondering the same thing. The googleMerchantId is _optional_ in Braintree Sandbox environments, but as part of getting any app accepted for Production you must first request a merchant id from Google then supply this in the GooglePaymentRequest (https://developers.braintreepayments.com/guides/drop-in/setup-and-integration/android/v3)? Other than forking this repository and making the necessary changes, I can't see a way to do this (unless I've missed something obvious?)

**Comment by mkharibalaji** [comment]
@soarb - You are correct.

**Comment by BradyShober** [comment]
As far as I can tell this would require updating the Android drop in UI version from 3 to 4, but this uses AndroidX dependencies so will not work in react-native versions prior to 0.60 which does not yet have a stable release.

**Comment by BradyShober** [comment]
As this package appears to be inactive currently, I've published a new package forked from this one with Google Pay support and some other fixes and improvements. https://github.com/BradyShober/react-native-braintree-dropin-ui
