### ISSUE TITLE
Please review your information and try again.

### ISSUE THREAD

**Issue by mukulkumar1703** [wgltony/react-native-braintree-dropin-ui#44]
Hi
Everything is working fine with sandbox details but getting "Please review your information and try again" error popup in the live app. Please provide any solution for this issue. Here is the screenshot.
![20200705_220713](https://user-images.githubusercontent.com/51224745/86563802-ad28b000-bf82-11ea-99f9-e2eff03de88a.jpg)

Environment
"react": 16.9.0
"react-native": 0.61.5
"react-native-braintree-dropin-ui": 1.0.9

**Comment by wgltony** [comment]
You can only use card information listed here to do testing.   :)

https://developers.braintreepayments.com/guides/credit-cards/testing-go-live/php

**Comment by mukulkumar1703** [comment]
Hi @wgltony , 
I am getting the above error with the Live card. It's working fine with the test cards.
