### ISSUE TITLE
iOS - Paypal popup not showing

### ISSUE THREAD

**Issue by Pandazaur** [wgltony/react-native-braintree-dropin-ui#45]
Hello,

## Packages used

```
"react-native-braintree-dropin-ui": "^1.0.9",
```

```
  pod 'CardIO'
  pod 'Braintree', '~> 4.32'
  pod 'BraintreeDropIn', '~> 8.1.1'
  pod 'Braintree/Apple-Pay'
  pod 'Braintree/PayPal'
  # pod 'Braintree/Venmo'

   # Data collector for Braintree Advanced Fraud Tools
  pod 'Braintree/DataCollector'
```

## Issue
When I'm opening the Braintree modal with "Credit Card" and "Paypal" options, when I'm clicking "Credit Card" everything is working. However, the paypal option is acting strangely: in dev mode ou release mode on simulator, the paypal popup appears and everything is OK, but when I'm trying on a real device, clicking on the "Paypal" option doesn't do anything and the bottomsheet closes.

The simulator and the real device both have iOS 13

Any idea to solve this issue ?

**Comment by piclez** [comment]
On my OS Simulator Paypal doesn't show anything as well, only Credit Card. Any ideas?

**Comment by Pandazaur** [comment]
Found the issue: check that you're using the good bundle ID !
An error message is missing to help.

**Comment by saraf22** [comment]
@Pandazaur can u please elaborate, how did u solve this?
i'm stuck here

**Comment by Pandazaur** [comment]
@saraf22 I checked the app bundle ID in the initialization when calling `Braintree.show()`
