### ISSUE TITLE
"Credit or Debit Cart" option is not showing in android.

### ISSUE THREAD

**Issue by kishanbharda** [wgltony/react-native-braintree-dropin-ui#52]
I have used this library in my react-native app. Here is the code that I have used to call react-native-braintree-dropin-ui :
```js
BraintreeDropIn.show({
  clientToken: brainTreeToken,
  countryCode: "US", //apple pay setting
  currencyCode: "USD", //apple pay setting
  orderTotal: cartAmount.toString(),
  googlePay: false,
  applePay: false,
  vaultManager: true,
  cardDisabled: false,
  darkTheme: true,
})
  .then((result) => {
    // here is an api to handle payment on server
  })
  .catch((error) => {
    if (error.code === "USER_CANCELLATION") {
      // code to handle user cancellation
    } else {
      // code to handle error
    }
  });
```

It successfully popup the braintree-dropin-ui. But the problem is that in android it only gives option to pay with paypal. It does not displaying "Credit or Debit Cart" option in pop up. However same code displaying both options, Paypal and Credit or Debit Cart in iOS.

Can anyone please help me what's the problem here ?

**Comment by amplework** [comment]
same issue

**Comment by mayur2345** [comment]
![Capture](https://user-images.githubusercontent.com/13624334/93125407-b6539d00-f6e8-11ea-916e-77cc6d5cc55b.PNG)

please remove the key cardDisabled from your option it will show because of the commented section it is showing such behaviour

**Comment by kishanbharda** [comment]
Thanks @mayur2345 it's worked. I removed `cardDisabled` key from the options and it worked.
