### ISSUE TITLE
credit or debit card option not coming android

### ISSUE THREAD

**Issue by mayur2345** [wgltony/react-native-braintree-dropin-ui#53]
Credit or debit card option is coming for ios but it is not coming for android.

**Comment by kishanbharda** [comment]
Duplicate of #52

**Comment by kishanbharda** [comment]
I think you have already solve it. Please close this issue.

**Comment by mayur2345** [comment]
solved 
https://github.com/wgltony/react-native-braintree-dropin-ui/issues/52
