### ISSUE TITLE
Circle CI Android build fail by react-native-braintree-dropin-ui

### ISSUE THREAD

**Issue by Bob-MYMC** [wgltony/react-native-braintree-dropin-ui#69]
* What went wrong:
Could not determine the dependencies of task ':react-native-braintree-dropin-ui:compileReleaseAidl'.
> Could not resolve all task dependencies for configuration ':react-native-braintree-dropin-ui:releaseCompileClasspath'.
   > Could not resolve org.jfrog.cardinalcommerce.gradle:cardinalmobilesdk:2.2.3-2.
     Required by:
         project :react-native-braintree-dropin-ui > com.braintreepayments.api:three-d-secure:3.11.1
      > Could not resolve org.jfrog.cardinalcommerce.gradle:cardinalmobilesdk:2.2.3-2.
         > Could not get resource 'https://cardinalcommerce.bintray.com/android/org/jfrog/cardinalcommerce/gradle/cardinalmobilesdk/2.2.3-2/cardinalmobilesdk-2.2.3-2.pom'.
            > Could not GET 'https://cardinalcommerce.bintray.com/android/org/jfrog/cardinalcommerce/gradle/cardinalmobilesdk/2.2.3-2/cardinalmobilesdk-2.2.3-2.pom'. Received status code 403 from server: Forbidden

**Comment by amplework** [comment]
facing same issue, have you got this resolved?

**Comment by Bob-MYMC** [comment]
@amplework hope this solution can help you.
https://stackoverflow.com/questions/60113189/braintree-drop-in-ui-error-failed-to-resolve-org-jfrog-cardinalcommerce-gradl
