### ISSUE TITLE
How do you disable PayPal as a payment method?

### ISSUE THREAD

**Issue by TommyHarty** [wgltony/react-native-braintree-dropin-ui#9]
The following does not work...

`BTDropInRequest *request = [[BTDropInRequest alloc] init];
request.paypalDisabled = YES;` 

...from https://developers.braintreepayments.com/guides/drop-in/setup-and-integration/ios/v4

**Comment by wgltony** [comment]
There are several ways to do it:
a. Disable Paypal Payment Processing from Braintree Account
b. Edit "ios/RNBraintreeDropIn.m" file,  add "request.paypalDisabled = YES;" at line 23, it should work.
c. In your Podfile comment the next line to disable PayPal
    #pod 'Braintree/PayPal'

**Comment by kishanbharda** [comment]
Thanks, It works on iOS, how to disable in android @wgltony  ?
